package-lock.json, package.json
**closes #27 *"
**Type of change**
**Description of change**
Old package.json
New package.json
**Implementation details**
Used npm audit fix --force for some updations
=> updates package.json ( closes#27)

CONTRIBUTORS.md, app/(components)/EditTicketForm.jsx
Closes #1 
fixes- When we try to update the tickets ,all fields get edited accordingly but description is not changing.
required changes have been done in app/(components)/EditTicketForm.jsx the file.
=> issue_1 Description Is not editing #1

app/(components)/TicketCard.jsx
Closes #6 
Adds red colour to cards which has priority greater than 4.
required changes in this app/(components)/TicketCard.jsx file.
=> issue_6 Add red colour to cards which has priority greater than 4 #6

app/page.jsx
Closes #25  
Replaced all instances of topics with tickets in page.jsx file.
>before
>after
=> Replaced all instances of topics with tickets in page.jsx file. Closes #25

app/(components)/EditTicketForm.jsx
Closes #7 
Uptill now our app has 4 categories only which are "Hardware Problem", Software Problem", "Application Development", "Project",.
Adds 2 more "Bug Fix" and "MVP"
required changes have been done in app/(components)/EditTicketForm.jsx file
=> Adding more categories 

app/(components)/EditTicketForm.jsx
Closes #10 
Progress slider can have a mark of 50 and 100 to easily assess where our status lies rather than choosing any point on the line.
required changes have been done in app/(components)/EditTicketForm.jsx this file.
=> added progress markers

app/page.jsx
Closes #11 
In a particular category , sort the tickets on the basis of their priority score rather than sorting them based on the time of creation.
required changes have been done in app/page.jsx .
=> sorts tickets on basis of priority, rather than time created

CONTRIBUTORS.md, package.json
Closes #28   
Changed name to Ticketify from "monday-tutorial"
N/A: This is a simple change to the JSON. 
N/A: This is a simple package JSON change.
=> Update Project Name in package.json to Reflect "Ticketify" (Issue_28)

app/page.jsx
Closes #5 
separates tickets by their status instead of category.
required changes have been done in app/page.jsx the file.
=> separates tickets by their status

app/page.jsx
Closes #56  
Adding a View by option with the following values:
- Category
- Status
[Screencast from 2024-12-22 03-11-39.webm](https://github.com/user-attachments/assets/9436a687-e51d-4c5a-a724-a1ea0cf05891)
=> Adding a view by option 

app/(components)/TicketCard.jsx
Closes #16 
Changed the default date format to en-IN (DD/MM/YYYY).
Implemented functionality to automatically detect the user's locality and display dates in the appropriate local format.
Changed the default date format to en-IN (DD/MM/YYYY).
Implemented functionality to automatically detect the user's locality and display dates in the appropriate local format. 
User timezone is fetched by Intl.DateTimeFormat().resolvedOptions().timeZone and added in options of date.toLocaleString()
At Indian TimeZone
At Australian TimeZone
=> Resolved Issue#16

app/page.jsx
Closes #18 
Adds filters to show tickets based on status (e.g., open, in-progress, closed).
required changes have been done in app/page.jsx file.
=> issue_18 Add Ticket Filters

app/(components)/EditTicketForm.jsx, app/models/Ticket.js
Closes #13   
Adds validations that will help prevent invalid or inconsistent data from being saved to the database.
required changes have been made in app/models/Ticket.js .
=> added validation to ticketSchema

README.md, app/api/Tickets/route.js
Closes issue #19 
Implemented pagination in the GET /api/Tickets route to limit results. Also edited readme file to change include tickets per page thing in env file.
Implemented pagination in the GET /api/Tickets route to limit results with help of `.limit()` and `.skip() `of mongoose. If there is no page and ticketsNo passed then all tickets are sent in response. Along with that there is default page set to 1 and default number of tickets as per .env file or 10 if not mentioned in .env file. 
Also edited readme file to change include tickets per page thing in env file.
=> Resolved issue #19. Implemented pagination in the GET /api/Tickets route to limit results

app/page.jsx, package-lock.json, package.json
Closes #48 
Disclosure widget feature has been created.
[Screencast from 2024-12-30 23-23-31.webm](https://github.com/user-attachments/assets/a262df34-550f-47ff-ac6a-d61499b6231c)
=> added disclosure widget issue_48

app/(components)/Nav.jsx
Closes #15 
Now it is clear from navbar which page is active: home page or create new ticket.
Now it is clear from navbar which page is active: home page or create new ticket. this is done with help of usePathname() function. The page which is open its icon is white colored and other is grey.
=> resolved issue#15 : on the navbar, now it is  clear if home is chosen or create ticket button is chosen

app/(components)/EditTicketForm.jsx
Closes #74  
Added a category "Backlog"
=> Added category Backlog

app/(components)/TicketCard.jsx
Closes #75 
The complete region of ticketcard is now clickable.
added the complete tickecard component in the `<Link>` component of HTML.
[Screencast from 2025-01-04 19-00-52.webm](https://github.com/user-attachments/assets/42eb594f-5614-4a8a-95fa-eb5acfc56a82)
=> made the whole ticket clickable

app/(components)/ProgressDisplay.jsx
Closes #78   
Adding div for progress percent beside the progress bar.
Added a parent for progress bar and percentage div(new).
=> issue_78 add percent div for ticket

app/(components)/EditTicketForm.jsx
Closes #77 
Fix the spelling of categories from "Application Deveopment" to "Application Development".
In EditTicketForm file corrected the spelling of  "Application Development" in categories.
=> issue_77 fix category spelling for  "Application Development"

app/(components)/NoTicketExistsCard.jsx, app/page.jsx
Closes #76 
Hence, add a spinning loading circle which instructs the users to wait for the tickets to be loaded.
Required changes have been made in NoTicketExistsCard.jsx file.
[Screencast from 2025-01-03 01-04-38.webm](https://github.com/user-attachments/assets/ca172714-cab6-4e5b-a394-0d80b5818309)
[Screencast from 2025-01-03 01-08-15.webm](https://github.com/user-attachments/assets/2f37e7cd-828a-408b-b2c9-cbc62895e9a1)
=> added loading feature
